apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: vault-secretstore-cluster
spec:
  provider:
    vault:
      server: "http://vault.default.svc.cluster.local:8200"  # Vault server address
      path: "secret"  # Vault KV path
      version: "v2"  # Vault KV version
      auth:
        tokenSecretRef:
          namespace: "default"
          name: "vault-token-secret"  # Name of the Kubernetes secret containing the Vault token
          key: "token"  # Key in the Kubernetes secret containing the Vault tokn
