---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vault-secret-cluster
  namespace: default
spec:
  encryptedData:
    vault-token: AgCOEuhDO5YQ9AnPWzAGCdEf8Nmbk0b+Vv4z1y3YkvSGauxjHXutYNOXPbNG8k1P94R8umTbIO5gZucK8SSja0fytBw2vycwKsCwSU///gUvNFQeQAp9ZQlFdi6G+KFG0rIn4wvdiu/REIANICjHEAO5tLRzliLC91KFAOVubcaleIi2Tl0YXWjoDwImNGZbYfGTSP92KSWxK/K8/7sfUa2Ip+flZs5IGflQqb2FI7SdtRpcZJlub1Zrq9w94nClT7zHlpirUCRht1fDM+yQbNJclBHoY+9KRx2l7pAgMGJppP9kpWauGRNSloDxm1AI2NPSFRBIH06ERIb9/pII1VfZPr/Tyqspb/GQ7fZ7l1nR+QB2yoNTc7TERZ57VEIO3FsgQHyoj17Lo8Hk6o2f9r/JBg4jwXnmzb5GJ8TZZotESI8TcRj3v0BlroRxGow5eKMLFwvkrV7iRYXyDZSSQIkUDc2QaS2nxtg4GdD5ZEpKsvqTxUDj1xWvQnjALburdq8/0NI/bVPB3O0OAwv7kIkn/h8t0LDsOZsLbqEgrP0KZJjGBNhi5csD5LveVCZQYjEe9Sz0qb9kaGUkaxAWuYJechS015+aEWILKXqloL/k8SzHdSD0aEkbNX7cSaby7G+jjhAX3vOIt4N2NhgVBSNiTJYHsWcpQg59j6UeC0UCbssL+kS0OqWa237D4uGdI9HpT8d7dg==
  template:
    metadata:
      creationTimestamp: null
      name: vault-secret-cluster
      namespace: default
