apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets-app
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/AmirMoshfeghi/gitops-cookbook-sc.git
      revision: main
      directories:
      - path: 'secret-management/sealed-secrets/*'
  template:
    metadata:
      name: '{{.path.basename}}'
      namespace: argocd
      labels:
         demo: sealed-secrets
    spec:
      project: "default"
      source:
        repoURL: https://github.com/AmirMoshfeghi/gitops-cookbook-sc.git
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'sealed'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
