apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: sealed
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5000
    protocol: TCP
  selector:
    app: {{ .Values.app.name }}
