replicaCount: 1

app:
  name: login-app
  namespace: sealed

image:
  repository: amirmoshfeghi/my-flux-demo
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

env:
  usernameSecret: sealed-secret
  usernameKey: username
  passwordSecret: sealed-secret
  passwordKey: password

resources: {}