apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: grafana-admin-external-secret
  namespace: external
spec:
  data:
  - remoteRef:
      key: secret/grafana-admin
      property: admin-user
    secretKey: admin-user
  - secretKey: admin-password
    remoteRef:
        key: secret/grafana-admin
        property: admin-password
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secretstore-cluster
  target:
    creationPolicy: Owner
    # deletionPolicy: Retain
    name: grafana-admin-secret
