apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: grafana-admin-external-secret
  namespace: external
spec:
  data:
  - remoteRef:
      key: secret/grafana-admin
      property: pass
    secretKey: token
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-secretstore-cluster
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: grafana-admin-secret
