apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: sealed
    server: 'https://kubernetes.default.svc'
  source:
    path: secret-management-demo/sealed-secrets-demo
    repoURL: 'https://github.com/AmirMoshfeghi/gitops-cookbook-sc.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true