apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/AmirMoshfeghi/gitops-cookbook-sc.git'
    targetRevision: HEAD
    path: secret-management-demo/sealed-secrets-demo/kustomize
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sealed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

