apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-admin-ex-secret
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AmirMoshfeghi/gitops-cookbook-sc.git
    path:  secret-management/external-secrets/grafana/external-secret
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: external
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

# Install grafana external secret
