apiVersion: v1
data:
  admin-password: SE9FU2toVG55TjZJNklNY09ZV3VMMkFsamFKUVhGYkIxWGdKUGpvVA==
  admin-user: YWRtaW4=
  ldap-toml: ""
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: my-grafana
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2024-07-03T12:42:28Z"
  labels:
    app.kubernetes.io/instance: my-grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.1.0
    helm.sh/chart: grafana-8.3.1
  name: my-grafana
  namespace: monitoring
  resourceVersion: "581"
  uid: ca51da42-1a7a-4653-8df9-771174176f38
type: Opaque
